#!/bin/sh

cd "$(dirname "$0")/Zend"

if [ "$1" = "--clean" -o "$1" = "-c" ]
	then
		make clean
		rm -rf .deps/
		rm -rf autom4te.cache/
	else
		sh ./buildconf
		sh ./configure

		automake
		make -j4
		cp .libs/libZend.a ../lib/libZend.a
fi
